# Generated by Django 5.2.8 on 2025-11-20 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='davr nomi')),
                ('start_date', models.DateField(verbose_name='davrning boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Davrning tugash vaqti')),
            ],
            options={
                'verbose_name': 'Davr',
                'verbose_name_plural': 'Davrlar',
            },
        ),
        migrations.CreateModel(
            name='Criterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Kriteriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kriteriyaning baholash tartibi')),
                ('max_score', models.IntegerField(verbose_name='Umumiy ball chegarasi')),
                ('durations', models.IntegerField(choices=[(6, '6 oy'), (12, '12 oy')], default=6, verbose_name='Natijani hisobga olish muddati')),
                ('role_type', models.CharField(choices=[('Ishchi', 'Ishchi'), ('Rahbar', 'Rahbar')], max_length=30, verbose_name='Kriteriya kimlar uchun')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kriteriyani tasdiqlaydigan hodim')),
            ],
            options={
                'verbose_name': 'Kriteriya',
                'verbose_name_plural': 'Kriteriyalar',
            },
        ),
        migrations.CreateModel(
            name='Submisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_file', models.FileField(blank=True, null=True, upload_to='datas/request', verbose_name='Dalil sifatidagi fayl')),
                ('request_description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_day', models.DateField(verbose_name='Kriteriya bajarilgan vaqt')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Bahoning izohi')),
                ('score', models.IntegerField(default=0, verbose_name='Baho')),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ("Ma'qullandi", "Ma'qullandi"), ('Rad etildi', 'Rad etildi')], default='Kutilmoqda', max_length=15)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.criterias', verbose_name='Kriteriya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to=settings.AUTH_USER_MODEL, verbose_name='Kriteriyani bajargan shaxs')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validator_submission', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlaydigan hodim')),
            ],
            options={
                'verbose_name': 'Taqdimnoma',
                'verbose_name_plural': 'Taqdimnomalar',
            },
        ),
    ]
