# Generated by Django 5.2.8 on 2025-11-21 04:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_submisson_validator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submisson',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='kpi.period', verbose_name='Qaysi davrga tegishli'),
        ),
        migrations.AlterField(
            model_name='criterias',
            name='max_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Umumiy ball chegarasi'),
        ),
        migrations.AlterField(
            model_name='submisson',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator_submission', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlaydigan hodim'),
        ),
    ]
