# Generated by Django 5.2.8 on 2025-11-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_submisson_period_alter_criterias_max_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submisson',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='submisson',
            name='period',
        ),
        migrations.RemoveField(
            model_name='submisson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submisson',
            name='validator',
        ),
        migrations.DeleteModel(
            name='Criterias',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Submisson',
        ),
    ]
