# Generated by Django 5.2.8 on 2025-11-21 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpi', '0004_remove_submisson_criteria_remove_submisson_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('max_score', models.IntegerField(verbose_name='Maksimal ball')),
            ],
            options={
                'verbose_name': 'Kriteriya turi',
                'verbose_name_plural': 'Kriteriya turlai',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Davr nomi')),
                ('type', models.CharField(blank=True, choices=[('Bir yil', 'Bir yil'), ('Birinchi 6 oylik', 'Birinchi 6 oylik'), ('Ikkinchi 6 oylik', 'Ikkinchi 6 oylik')], max_length=20, verbose_name='Davr turi')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('start_date', models.DateField(verbose_name='Davrning boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Davrning tugash sanasi')),
            ],
            options={
                'verbose_name': 'Davr',
                'verbose_name_plural': 'Davrlar',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_num', models.CharField(max_length=10, verbose_name='Punkt')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('full_description', models.TextField(verbose_name="To'liq izoh")),
                ('duration_type', models.CharField(choices=[('Bir yil', 'Bir yil'), ('Birinchi 6 oylik', 'Birinchi 6 oylik'), ('Ikkinchi 6 oylik', 'Ikkinchi 6 oylik')], max_length=20, verbose_name='Natijalarni hisobga olish muddati')),
                ('max_score', models.IntegerField(verbose_name='maksimal ball')),
                ('validator', models.ForeignKey(help_text='Qabul qilish yoki rad qilish huquqi', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Masul shaxs')),
            ],
            options={
                'verbose_name': 'Kriteriya',
                'verbose_name_plural': 'Kriteriyalar',
            },
        ),
        migrations.CreateModel(
            name='CriteriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('max_score', models.IntegerField(verbose_name='Maksimal ball')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.criteria', verbose_name='Kriteriya')),
            ],
            options={
                'verbose_name': 'Kriteriya qismlari',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_file', models.FileField(blank=True, null=True, upload_to='datas/request', verbose_name='Dalil sifatidagi fayl')),
                ('request_description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_day', models.DateField(verbose_name='Kriteriya bajarilgan vaqt')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Bahoning izohi')),
                ('score', models.IntegerField(default=0, verbose_name='Baho')),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ("Ma'qullandi", "Ma'qullandi"), ('Rad etildi', 'Rad etildi')], default='Kutilmoqda', max_length=15)),
                ('criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.criteriaitem', verbose_name='Kriteriya qismi')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi.period', verbose_name='Qaysi davrga tegishli')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to=settings.AUTH_USER_MODEL, verbose_name='Kriteriyani bajargan shaxs')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator_submission', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlaydigan hodim')),
            ],
            options={
                'verbose_name': "Ma'lumotnoma",
                'verbose_name_plural': "Ma'lumotnoma",
            },
        ),
    ]
