# Generated by Django 5.2.8 on 2025-11-21 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriaitem',
            options={'ordering': ('id',), 'verbose_name': 'Kriteriya qismi', 'verbose_name_plural': 'Kriteriya qismlari'},
        ),
        migrations.AddField(
            model_name='criteria',
            name='criteria_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kpi.criteriatype', verbose_name='Kriteriya turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criteria',
            name='duration_type',
            field=models.CharField(choices=[('Bir yil', 'Bir yil'), ('6 oylik', '6 oylik')], max_length=20, verbose_name='Natijalarni hisobga olish muddati'),
        ),
        migrations.AlterField(
            model_name='period',
            name='type',
            field=models.CharField(blank=True, choices=[('Bir yil', 'Bir yil'), ('6 oylik', '6 oylik')], max_length=20, verbose_name='Davr turi'),
        ),
    ]
