# Generated by Django 5.2.8 on 2025-11-21 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_alter_criteriaitem_options_criteria_criteria_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ['item_num'], 'verbose_name': 'Kriteriya', 'verbose_name_plural': 'Kriteriyalar'},
        ),
        migrations.CreateModel(
            name='ScoreCriteriaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(verbose_name='Umumiy ball')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.criteria', verbose_name='Kriteriya')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.period', verbose_name='Davr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ball',
                'verbose_name_plural': 'Ballar',
            },
        ),
    ]
