# Generated by Django 5.2.8 on 2025-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_alter_criteria_options_scorecriteriauser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['id'], 'verbose_name': 'Davr', 'verbose_name_plural': 'Davrlar'},
        ),
        migrations.AlterField(
            model_name='scorecriteriauser',
            name='ball',
            field=models.IntegerField(default=0, verbose_name='Umumiy ball'),
        ),
    ]
